/**
 * FeelFit v10 — Static Medicine Database
 * 100+ medicines across 15 categories with full metadata.
 * Used by MedicineTab for instant local search (no API call needed),
 * with the LLM service as fallback for anything not found here.
 */

export interface MedicineEntry {
  id: string;
  name: string;
  generic: string;
  brands: string[];
  category: MedCategory;
  usage: string;
  dosage: string;
  sideEffects: string[];
  warnings: string[];
  interactions: string[];
  prescription: boolean;
  storage: string;
  alternatives: string[];
}

export type MedCategory =
  | 'Pain Relief'
  | 'Fever'
  | 'Cold & Flu'
  | 'Allergy'
  | 'Diabetes'
  | 'Blood Pressure'
  | 'Heart Health'
  | 'Vitamins & Supplements'
  | 'Digestive Health'
  | 'Antibiotics'
  | 'Skin Care'
  | 'Mental Health'
  | 'Respiratory Health'
  | 'Women\'s Health'
  | 'Children\'s Medicines';

export const MED_CATEGORIES: MedCategory[] = [
  'Pain Relief', 'Fever', 'Cold & Flu', 'Allergy', 'Diabetes',
  'Blood Pressure', 'Heart Health', 'Vitamins & Supplements',
  'Digestive Health', 'Antibiotics', 'Skin Care', 'Mental Health',
  'Respiratory Health', 'Women\'s Health', 'Children\'s Medicines',
];

export const MEDICINE_DB: MedicineEntry[] = [
  // ── PAIN RELIEF ────────────────────────────────────────────────────────────
  {
    id: 'paracetamol', name: 'Paracetamol', generic: 'Acetaminophen',
    brands: ['Crocin', 'Dolo 650', 'Calpol', 'Panadol', 'Tylenol'],
    category: 'Pain Relief',
    usage: 'Relief of mild to moderate pain including headache, dental pain, back pain, muscle aches, and fever reduction.',
    dosage: 'Adults: 500–1000 mg every 4–6 hours as needed. Max 4000 mg per day. Children: 10–15 mg/kg every 4–6 hours.',
    sideEffects: ['Nausea', 'Stomach pain (rare at normal doses)', 'Liver damage with overdose', 'Skin rash (rare)'],
    warnings: ['Do not exceed 4g/day', 'Avoid alcohol use', 'Caution in liver disease', 'Check all other medicines for hidden paracetamol content'],
    interactions: ['Alcohol', 'Warfarin', 'Isoniazid', 'Carbamazepine'],
    prescription: false,
    storage: 'Store below 25°C, away from moisture.',
    alternatives: ['Ibuprofen', 'Aspirin', 'Diclofenac'],
  },
  {
    id: 'ibuprofen', name: 'Ibuprofen', generic: 'Ibuprofen',
    brands: ['Brufen', 'Advil', 'Combiflam (with paracetamol)', 'Nurofen'],
    category: 'Pain Relief',
    usage: 'Anti-inflammatory pain relief for arthritis, dental pain, menstrual cramps, sports injuries, and fever.',
    dosage: 'Adults: 200–400 mg every 4–6 hours. Max 1200 mg OTC / 3200 mg prescribed per day.',
    sideEffects: ['Stomach upset', 'Heartburn', 'Nausea', 'Dizziness', 'Fluid retention', 'Increased blood pressure'],
    warnings: ['Take with food', 'Avoid in peptic ulcer disease', 'Caution in kidney disease', 'Avoid in last trimester of pregnancy'],
    interactions: ['Aspirin', 'Warfarin', 'Lithium', 'ACE inhibitors', 'Diuretics'],
    prescription: false,
    storage: 'Store below 30°C in dry place.',
    alternatives: ['Paracetamol', 'Naproxen', 'Diclofenac'],
  },
  {
    id: 'diclofenac', name: 'Diclofenac', generic: 'Diclofenac sodium',
    brands: ['Voveran', 'Voltaren', 'Diclofenac SR'],
    category: 'Pain Relief',
    usage: 'Moderate to severe pain from musculoskeletal conditions, osteoarthritis, rheumatoid arthritis, post-surgical pain.',
    dosage: 'Adults: 50 mg 2–3 times daily OR 75 mg SR once daily. Apply gel form to affected area 3–4 times daily.',
    sideEffects: ['GI discomfort', 'Headache', 'Dizziness', 'Elevated liver enzymes', 'Fluid retention'],
    warnings: ['Avoid if history of peptic ulcer', 'Monitor liver function in long-term use', 'Cardiovascular risk with prolonged use'],
    interactions: ['Aspirin', 'ACE inhibitors', 'Diuretics', 'Lithium', 'Methotrexate'],
    prescription: true,
    storage: 'Store below 25°C, protect from light.',
    alternatives: ['Ibuprofen', 'Naproxen', 'Celecoxib'],
  },
  {
    id: 'aspirin', name: 'Aspirin', generic: 'Acetylsalicylic acid',
    brands: ['Disprin', 'Ecosprin', 'Aspirin Cardio'],
    category: 'Pain Relief',
    usage: 'Pain relief, fever, anti-inflammatory. Low dose (75 mg) used for cardiovascular protection and stroke prevention.',
    dosage: 'Pain/fever: 300–900 mg every 4–6 hours. Cardiovascular: 75–150 mg once daily.',
    sideEffects: ['Stomach irritation', 'GI bleeding', 'Tinnitus (high doses)', 'Bruising'],
    warnings: ['Avoid in children under 16 (Reye\'s syndrome risk)', 'Avoid in peptic ulcer', 'Stop 7 days before surgery'],
    interactions: ['Warfarin', 'Ibuprofen', 'Methotrexate', 'ACE inhibitors'],
    prescription: false,
    storage: 'Store in cool, dry place away from moisture.',
    alternatives: ['Paracetamol', 'Ibuprofen', 'Clopidogrel (for CV use)'],
  },
  {
    id: 'tramadol', name: 'Tramadol', generic: 'Tramadol hydrochloride',
    brands: ['Ultram', 'Tramazac', 'Tramacip'],
    category: 'Pain Relief',
    usage: 'Moderate to severe pain where other analgesics are inadequate. Post-operative pain, cancer pain, neuropathic pain.',
    dosage: 'Adults: 50–100 mg every 4–6 hours. Max 400 mg/day. Extended-release: 100–300 mg once daily.',
    sideEffects: ['Nausea', 'Dizziness', 'Constipation', 'Drowsiness', 'Headache', 'Sweating'],
    warnings: ['Risk of dependence', 'Avoid with alcohol', 'Avoid in seizure disorders', 'Not for children under 12'],
    interactions: ['MAO inhibitors', 'SSRIs', 'CNS depressants', 'Alcohol'],
    prescription: true,
    storage: 'Store at room temperature, away from moisture and heat.',
    alternatives: ['Codeine', 'Tapentadol', 'Strong NSAIDs'],
  },
  {
    id: 'naproxen', name: 'Naproxen', generic: 'Naproxen',
    brands: ['Naprosyn', 'Aleve', 'Synflex'],
    category: 'Pain Relief',
    usage: 'Arthritis, menstrual cramps, muscle aches, back pain, headaches. Longer-acting than ibuprofen.',
    dosage: 'Adults: 250–500 mg twice daily. OTC: 220 mg every 8–12 hours. Max 660 mg OTC per day.',
    sideEffects: ['Heartburn', 'Nausea', 'Headache', 'Drowsiness', 'Dizziness'],
    warnings: ['Avoid with other NSAIDs', 'Caution in kidney disease', 'Not recommended in pregnancy'],
    interactions: ['Aspirin', 'Blood thinners', 'Lithium', 'Methotrexate'],
    prescription: false,
    storage: 'Store below 25°C in a dry place.',
    alternatives: ['Ibuprofen', 'Diclofenac', 'Celecoxib'],
  },

  // ── FEVER ──────────────────────────────────────────────────────────────────
  {
    id: 'mefenamic', name: 'Mefenamic Acid', generic: 'Mefenamic acid',
    brands: ['Meftal', 'Ponstan', 'Meftal-Forte'],
    category: 'Fever',
    usage: 'Fever, pain relief especially dysmenorrhea (period pain), mild to moderate pain.',
    dosage: 'Adults: 500 mg three times daily after meals. Short-term use (up to 7 days).',
    sideEffects: ['Stomach upset', 'Diarrhea', 'Nausea', 'Headache', 'Dizziness'],
    warnings: ['Take with food', 'Avoid in peptic ulcer', 'Not for more than 7 days', 'Avoid in kidney disease'],
    interactions: ['Warfarin', 'Lithium', 'Oral antidiabetics'],
    prescription: false,
    storage: 'Store below 30°C, protect from moisture.',
    alternatives: ['Ibuprofen', 'Paracetamol', 'Naproxen'],
  },
  {
    id: 'nimesulide', name: 'Nimesulide', generic: 'Nimesulide',
    brands: ['Nise', 'Nimulid', 'Nimica'],
    category: 'Fever',
    usage: 'Fever, pain, and inflammation. Popular in India for acute pain management.',
    dosage: 'Adults: 100 mg twice daily after meals. Max 200 mg/day. Short-term use only.',
    sideEffects: ['Stomach pain', 'Nausea', 'Liver toxicity (rare but serious)', 'Dizziness'],
    warnings: ['Not for children under 12', 'Avoid in liver disease', 'Not for more than 15 days', 'Avoid in pregnancy'],
    interactions: ['Warfarin', 'Diuretics', 'Ciclosporin'],
    prescription: false,
    storage: 'Store in cool, dry place below 30°C.',
    alternatives: ['Paracetamol', 'Ibuprofen', 'Mefenamic acid'],
  },

  // ── COLD & FLU ─────────────────────────────────────────────────────────────
  {
    id: 'cetirizine', name: 'Cetirizine', generic: 'Cetirizine hydrochloride',
    brands: ['Zyrtec', 'Cetzine', 'Alerid', 'Okacet'],
    category: 'Cold & Flu',
    usage: 'Relief of allergy symptoms: sneezing, runny nose, watery eyes. Also helps with hives and cold symptoms.',
    dosage: 'Adults & children 6+: 10 mg once daily. Children 2–6 years: 5 mg once daily.',
    sideEffects: ['Drowsiness (less than older antihistamines)', 'Dry mouth', 'Headache', 'Fatigue'],
    warnings: ['Avoid alcohol', 'Caution when driving', 'Reduce dose in kidney disease'],
    interactions: ['Alcohol', 'CNS depressants', 'Theophylline'],
    prescription: false,
    storage: 'Store below 30°C, away from moisture.',
    alternatives: ['Loratadine', 'Fexofenadine', 'Levocetirizine'],
  },
  {
    id: 'loratadine', name: 'Loratadine', generic: 'Loratadine',
    brands: ['Claritin', 'Lorfast', 'Clarityn'],
    category: 'Cold & Flu',
    usage: 'Non-drowsy antihistamine for allergic rhinitis, hay fever, and chronic hives.',
    dosage: 'Adults: 10 mg once daily. Children 2–12: 5 mg (syrup) once daily.',
    sideEffects: ['Headache', 'Dry mouth', 'Drowsiness (rare)', 'Fatigue'],
    warnings: ['Reduce dose in liver disease', 'Generally safe for driving'],
    interactions: ['Ketoconazole', 'Erythromycin', 'Cimetidine'],
    prescription: false,
    storage: 'Store at room temperature away from heat and moisture.',
    alternatives: ['Cetirizine', 'Fexofenadine', 'Desloratadine'],
  },
  {
    id: 'phenylephrine', name: 'Phenylephrine', generic: 'Phenylephrine hydrochloride',
    brands: ['Sudafed PE', 'Dristan'],
    category: 'Cold & Flu',
    usage: 'Nasal decongestant for blocked nose due to cold, sinusitis, or allergies.',
    dosage: 'Adults: 10 mg every 4 hours. Max 60 mg/day. Do not use for more than 3 days.',
    sideEffects: ['Increased blood pressure', 'Headache', 'Nervousness', 'Insomnia', 'Palpitations'],
    warnings: ['Avoid in high blood pressure', 'Avoid in heart disease', 'Not for children under 12 in OTC form'],
    interactions: ['MAO inhibitors', 'Beta-blockers', 'Other decongestants'],
    prescription: false,
    storage: 'Store at room temperature.',
    alternatives: ['Xylometazoline (nasal spray)', 'Pseudoephedrine', 'Saline nasal spray'],
  },
  {
    id: 'dextromethorphan', name: 'Dextromethorphan', generic: 'Dextromethorphan hydrobromide',
    brands: ['Benadryl DX', 'Robitussin DX', 'Delsym'],
    category: 'Cold & Flu',
    usage: 'Cough suppressant for dry, non-productive cough associated with cold and flu.',
    dosage: 'Adults: 15–30 mg every 4–6 hours. Max 120 mg/day. Children 6–12: 7.5–15 mg every 6–8 hours.',
    sideEffects: ['Drowsiness', 'Dizziness', 'Nausea', 'Constipation'],
    warnings: ['Do not use with MAO inhibitors', 'Avoid in productive cough', 'Caution in liver disease'],
    interactions: ['MAO inhibitors', 'SSRIs', 'Alcohol'],
    prescription: false,
    storage: 'Store below 25°C.',
    alternatives: ['Guaifenesin (for productive cough)', 'Codeine linctus', 'Honey and lemon (mild)'],
  },
  {
    id: 'guaifenesin', name: 'Guaifenesin', generic: 'Guaifenesin',
    brands: ['Mucinex', 'Grilinctus', 'Ascoril (combination)'],
    category: 'Cold & Flu',
    usage: 'Expectorant — thins and loosens mucus, making coughs more productive and easier to clear.',
    dosage: 'Adults: 200–400 mg every 4 hours. Extended-release: 600–1200 mg every 12 hours.',
    sideEffects: ['Nausea', 'Vomiting', 'Dizziness', 'Headache'],
    warnings: ['Drink plenty of water', 'Avoid in children under 2', 'Do not exceed recommended dose'],
    interactions: ['Blood thinners (mild effect)'],
    prescription: false,
    storage: 'Store at room temperature.',
    alternatives: ['N-acetylcysteine', 'Bromhexine', 'Steam inhalation'],
  },

  // ── ALLERGY ────────────────────────────────────────────────────────────────
  {
    id: 'fexofenadine', name: 'Fexofenadine', generic: 'Fexofenadine hydrochloride',
    brands: ['Allegra', 'Fastofen', 'Fexova'],
    category: 'Allergy',
    usage: 'Non-drowsy antihistamine for seasonal allergic rhinitis, chronic urticaria, and hay fever.',
    dosage: 'Adults: 120 mg once or 60 mg twice daily. Children 6–11: 30 mg twice daily.',
    sideEffects: ['Headache', 'Nausea', 'Drowsiness (minimal)', 'Dizziness'],
    warnings: ['Avoid grapefruit juice', 'Avoid antacids containing aluminum/magnesium'],
    interactions: ['Grapefruit juice', 'Antacids', 'Ketoconazole', 'Erythromycin'],
    prescription: false,
    storage: 'Store below 30°C away from moisture and heat.',
    alternatives: ['Cetirizine', 'Loratadine', 'Levocetirizine'],
  },
  {
    id: 'montelukast', name: 'Montelukast', generic: 'Montelukast sodium',
    brands: ['Singulair', 'Montair', 'Telekast'],
    category: 'Allergy',
    usage: 'Prevention of allergy symptoms and asthma. Also used for exercise-induced bronchoconstriction.',
    dosage: 'Adults: 10 mg once daily in the evening. Children 6–14: 5 mg chewable. Children 2–5: 4 mg.',
    sideEffects: ['Headache', 'Stomach pain', 'Diarrhea', 'Mood changes (rare)', 'Vivid dreams'],
    warnings: ['Rare neuropsychiatric events (anxiety, depression, suicidal thoughts) — monitor', 'Not for acute asthma attacks'],
    interactions: ['Phenobarbital', 'Rifampicin', 'Gemfibrozil'],
    prescription: true,
    storage: 'Store at room temperature, protect from light and moisture.',
    alternatives: ['Antihistamines', 'Inhaled corticosteroids', 'Cromolyn sodium'],
  },
  {
    id: 'chlorpheniramine', name: 'Chlorpheniramine', generic: 'Chlorphenamine maleate',
    brands: ['Piriton', 'CTM', 'Polaramine'],
    category: 'Allergy',
    usage: 'Allergic reactions, hay fever, hives, insect bites, anaphylaxis (adjunct treatment).',
    dosage: 'Adults: 4 mg every 4–6 hours. Max 24 mg/day. Children 6–12: 2 mg every 4–6 hours.',
    sideEffects: ['Significant drowsiness', 'Dry mouth', 'Urinary retention', 'Blurred vision'],
    warnings: ['Sedating — avoid driving', 'Avoid alcohol', 'Caution in prostate enlargement, glaucoma'],
    interactions: ['Alcohol', 'CNS depressants', 'MAO inhibitors'],
    prescription: false,
    storage: 'Store below 30°C.',
    alternatives: ['Cetirizine', 'Loratadine', 'Fexofenadine'],
  },
  {
    id: 'hydrocortisone-cream', name: 'Hydrocortisone Cream', generic: 'Hydrocortisone',
    brands: ['Cortaid', 'HC-Pram', 'Dermacort'],
    category: 'Allergy',
    usage: 'Topical treatment for allergic skin reactions, eczema, contact dermatitis, insect bites, mild psoriasis.',
    dosage: 'Apply thin layer to affected area 1–4 times daily. Use the lowest effective strength.',
    sideEffects: ['Skin thinning with prolonged use', 'Stretch marks', 'Redness', 'Acne-like rash'],
    warnings: ['Do not use on face for more than 7 days', 'Do not apply to broken skin', 'Avoid in fungal infections'],
    interactions: ['Other topical steroids'],
    prescription: false,
    storage: 'Store below 25°C.',
    alternatives: ['Betamethasone cream', 'Triamcinolone cream', 'Calamine lotion'],
  },

  // ── DIABETES ───────────────────────────────────────────────────────────────
  {
    id: 'metformin', name: 'Metformin', generic: 'Metformin hydrochloride',
    brands: ['Glucophage', 'Glycomet', 'Obimet', 'Gluconorm'],
    category: 'Diabetes',
    usage: 'First-line treatment for type 2 diabetes. Reduces blood glucose by decreasing hepatic glucose production.',
    dosage: 'Start: 500 mg twice daily with meals. Usual: 1000–2000 mg/day in divided doses. Max 2500 mg/day.',
    sideEffects: ['Nausea', 'Diarrhea', 'Stomach upset (usually improve over time)', 'Vitamin B12 deficiency (long-term)', 'Metallic taste'],
    warnings: ['Hold before contrast-dye procedures', 'Avoid in severe kidney disease (eGFR <30)', 'Risk of lactic acidosis (rare)', 'Avoid excess alcohol'],
    interactions: ['Alcohol', 'Contrast dye', 'Cimetidine', 'Topiramate'],
    prescription: true,
    storage: 'Store at room temperature, away from moisture.',
    alternatives: ['Glipizide', 'Sitagliptin', 'Empagliflozin'],
  },
  {
    id: 'glipizide', name: 'Glipizide', generic: 'Glipizide',
    brands: ['Glucotrol', 'Glynase', 'Minidiab'],
    category: 'Diabetes',
    usage: 'Type 2 diabetes — stimulates the pancreas to produce more insulin.',
    dosage: 'Start: 5 mg once daily before breakfast. Usual: 10–20 mg/day. Max 40 mg/day.',
    sideEffects: ['Hypoglycemia (low blood sugar)', 'Weight gain', 'Nausea', 'Dizziness', 'Skin rash'],
    warnings: ['Monitor blood glucose regularly', 'Risk of hypoglycemia if meal is skipped', 'Avoid in severe liver/kidney disease'],
    interactions: ['Alcohol', 'NSAIDs', 'Warfarin', 'Fluconazole', 'Beta-blockers (mask hypoglycemia symptoms)'],
    prescription: true,
    storage: 'Store at room temperature, protect from moisture.',
    alternatives: ['Metformin', 'Glimepiride', 'Sitagliptin'],
  },
  {
    id: 'sitagliptin', name: 'Sitagliptin', generic: 'Sitagliptin',
    brands: ['Januvia', 'Zitamet', 'Istavel'],
    category: 'Diabetes',
    usage: 'Type 2 diabetes. DPP-4 inhibitor that helps regulate blood sugar after meals.',
    dosage: 'Adults: 100 mg once daily. Reduce to 50 mg if eGFR 30–50, 25 mg if <30.',
    sideEffects: ['Runny nose', 'Sore throat', 'Upper respiratory infection', 'Pancreatitis (rare)'],
    warnings: ['Risk of pancreatitis — discontinue if suspected', 'May cause joint pain', 'Reduce dose in kidney impairment'],
    interactions: ['Digoxin', 'CYP3A4 inducers'],
    prescription: true,
    storage: 'Store at room temperature.',
    alternatives: ['Metformin', 'Empagliflozin', 'Liraglutide'],
  },
  {
    id: 'empagliflozin', name: 'Empagliflozin', generic: 'Empagliflozin',
    brands: ['Jardiance', 'Synjardy (with metformin)'],
    category: 'Diabetes',
    usage: 'Type 2 diabetes and cardiovascular risk reduction. SGLT-2 inhibitor — removes glucose via kidneys.',
    dosage: 'Start: 10 mg once daily in the morning. May increase to 25 mg. Take with or without food.',
    sideEffects: ['Genital fungal infections', 'Urinary tract infections', 'Increased urination', 'Dehydration', 'Ketoacidosis (rare)'],
    warnings: ['Hold before major surgery', 'Avoid in severe kidney impairment', 'Risk of DKA — seek care for persistent nausea/vomiting'],
    interactions: ['Diuretics', 'Insulin (hypoglycemia risk)'],
    prescription: true,
    storage: 'Store below 30°C.',
    alternatives: ['Metformin', 'Sitagliptin', 'Dapagliflozin'],
  },
  {
    id: 'insulin-glargine', name: 'Insulin Glargine', generic: 'Insulin glargine',
    brands: ['Lantus', 'Toujeo', 'Basalog'],
    category: 'Diabetes',
    usage: 'Long-acting basal insulin for type 1 and type 2 diabetes. Provides steady 24-hour coverage.',
    dosage: 'Dose is individualized. Typical start: 10 units or 0.2 units/kg once daily at same time each day.',
    sideEffects: ['Hypoglycemia', 'Injection site reactions', 'Weight gain', 'Lipodystrophy at injection sites'],
    warnings: ['Do not mix with other insulins', 'Rotate injection sites', 'Monitor blood glucose closely when changing insulin regimens'],
    interactions: ['Alcohol', 'Beta-blockers', 'Thiazolidinediones', 'Oral antidiabetics'],
    prescription: true,
    storage: 'Unopened: refrigerate (2–8°C). In use: room temperature up to 28 days.',
    alternatives: ['Insulin detemir', 'NPH insulin', 'Insulin degludec'],
  },

  // ── BLOOD PRESSURE ─────────────────────────────────────────────────────────
  {
    id: 'amlodipine', name: 'Amlodipine', generic: 'Amlodipine besylate',
    brands: ['Norvasc', 'Amlong', 'Amlip', 'Stamlo'],
    category: 'Blood Pressure',
    usage: 'High blood pressure (hypertension) and angina. Calcium channel blocker that relaxes blood vessels.',
    dosage: 'Start: 5 mg once daily. May increase to 10 mg once daily after 7–14 days.',
    sideEffects: ['Ankle swelling', 'Flushing', 'Headache', 'Palpitations', 'Fatigue', 'Gingival hyperplasia'],
    warnings: ['Ankle swelling is common — does not usually indicate heart failure', 'Abrupt discontinuation may worsen angina'],
    interactions: ['Simvastatin (increase to 20 mg limit)', 'Cyclosporin', 'Tacrolimus'],
    prescription: true,
    storage: 'Store at room temperature, away from moisture.',
    alternatives: ['Nifedipine', 'Felodipine', 'ACE inhibitors'],
  },
  {
    id: 'ramipril', name: 'Ramipril', generic: 'Ramipril',
    brands: ['Altace', 'Cardace', 'Ramace', 'Hopace'],
    category: 'Blood Pressure',
    usage: 'Hypertension, heart failure, post-MI cardioprotection, diabetic nephropathy protection.',
    dosage: 'Start: 2.5 mg once daily. Usual: 5–10 mg once daily. Max 10 mg/day.',
    sideEffects: ['Persistent dry cough (5–20%)', 'Dizziness', 'Hyperkalemia', 'Angioedema (rare but serious)'],
    warnings: ['Stop if angioedema develops (throat/tongue swelling)', 'Avoid in pregnancy', 'Monitor potassium and kidney function'],
    interactions: ['NSAIDs', 'Potassium supplements', 'Spironolactone', 'Lithium'],
    prescription: true,
    storage: 'Store below 25°C, protect from moisture.',
    alternatives: ['Enalapril', 'Lisinopril', 'Losartan (if cough occurs)'],
  },
  {
    id: 'losartan', name: 'Losartan', generic: 'Losartan potassium',
    brands: ['Cozaar', 'Losacar', 'Repace', 'Covance'],
    category: 'Blood Pressure',
    usage: 'Hypertension, diabetic kidney disease, heart failure, stroke prevention in patients with LVH.',
    dosage: 'Start: 50 mg once daily. May increase to 100 mg once daily.',
    sideEffects: ['Dizziness', 'Hyperkalemia', 'Back pain', 'Upper respiratory infections'],
    warnings: ['Avoid in pregnancy', 'Monitor potassium and kidney function', 'First dose may cause significant drop in BP'],
    interactions: ['NSAIDs', 'Potassium supplements', 'Lithium', 'ACE inhibitors'],
    prescription: true,
    storage: 'Store at room temperature away from moisture.',
    alternatives: ['Valsartan', 'Olmesartan', 'Ramipril'],
  },
  {
    id: 'atenolol', name: 'Atenolol', generic: 'Atenolol',
    brands: ['Tenormin', 'Aten', 'Betacard'],
    category: 'Blood Pressure',
    usage: 'Hypertension, angina, heart rhythm disorders, post-MI management.',
    dosage: 'Hypertension: 25–100 mg once daily. Max 100 mg/day. Angina: 100 mg once or 50 mg twice daily.',
    sideEffects: ['Fatigue', 'Cold hands/feet', 'Bradycardia', 'Sleep disturbance', 'Reduced exercise tolerance'],
    warnings: ['Do not stop suddenly (risk of rebound angina/MI)', 'May mask hypoglycemia signs in diabetics', 'Caution in asthma/COPD'],
    interactions: ['Verapamil', 'Diltiazem', 'Clonidine', 'NSAIDs'],
    prescription: true,
    storage: 'Store at room temperature, away from moisture.',
    alternatives: ['Metoprolol', 'Bisoprolol', 'Amlodipine'],
  },
  {
    id: 'telmisartan', name: 'Telmisartan', generic: 'Telmisartan',
    brands: ['Micardis', 'Telmikind', 'Telma'],
    category: 'Blood Pressure',
    usage: 'Hypertension and cardiovascular risk reduction in high-risk patients.',
    dosage: 'Start: 40 mg once daily. May adjust to 20–80 mg once daily.',
    sideEffects: ['Back pain', 'Diarrhea', 'Dizziness', 'Sinusitis'],
    warnings: ['Avoid in pregnancy', 'Caution in liver/kidney impairment', 'Monitor potassium levels'],
    interactions: ['Lithium', 'NSAIDs', 'ACE inhibitors'],
    prescription: true,
    storage: 'Store below 30°C in dry place.',
    alternatives: ['Losartan', 'Valsartan', 'Candesartan'],
  },

  // ── HEART HEALTH ───────────────────────────────────────────────────────────
  {
    id: 'atorvastatin', name: 'Atorvastatin', generic: 'Atorvastatin calcium',
    brands: ['Lipitor', 'Storvas', 'Atorva', 'Aztor'],
    category: 'Heart Health',
    usage: 'High LDL cholesterol, prevention of cardiovascular events (heart attack, stroke) in high-risk patients.',
    dosage: 'Start: 10–20 mg once daily at any time. Range 10–80 mg/day. High-intensity: 40–80 mg.',
    sideEffects: ['Muscle pain (myalgia)', 'Elevated liver enzymes', 'Headache', 'GI upset', 'Myopathy (rare)'],
    warnings: ['Report unexplained muscle pain — risk of rhabdomyolysis', 'Monitor liver function', 'Avoid pregnancy', 'Limit alcohol'],
    interactions: ['Gemfibrozil', 'Cyclosporin', 'Clarithromycin', 'Grapefruit juice'],
    prescription: true,
    storage: 'Store at room temperature.',
    alternatives: ['Rosuvastatin', 'Simvastatin', 'Pitavastatin'],
  },
  {
    id: 'rosuvastatin', name: 'Rosuvastatin', generic: 'Rosuvastatin calcium',
    brands: ['Crestor', 'Rozavel', 'Rosumac'],
    category: 'Heart Health',
    usage: 'High cholesterol, mixed dyslipidemia, primary prevention of cardiovascular disease.',
    dosage: 'Start: 5–10 mg once daily. Range 5–40 mg/day. Asian patients: start at 5 mg.',
    sideEffects: ['Muscle pain', 'Headache', 'Abdominal pain', 'Weakness', 'Nausea'],
    warnings: ['Lower doses for Asian patients (CYP2C9 polymorphism)', 'Monitor for muscle pain', 'Avoid in pregnancy'],
    interactions: ['Gemfibrozil', 'Cyclosporin', 'Antacids (reduce absorption)', 'Warfarin'],
    prescription: true,
    storage: 'Store at room temperature, protect from light.',
    alternatives: ['Atorvastatin', 'Pitavastatin', 'Ezetimibe'],
  },
  {
    id: 'clopidogrel', name: 'Clopidogrel', generic: 'Clopidogrel bisulfate',
    brands: ['Plavix', 'Clopilet', 'Clopivas'],
    category: 'Heart Health',
    usage: 'Prevention of blood clots after heart attack, stroke, peripheral artery disease, and coronary stent placement.',
    dosage: 'ACS: Loading 300–600 mg, then 75 mg once daily. Prevention: 75 mg once daily.',
    sideEffects: ['Bleeding (GI, bruising)', 'Rash', 'Diarrhea', 'Headache'],
    warnings: ['Increased bleeding risk — especially GI', 'Avoid with omeprazole (reduces efficacy)', 'Do not stop without consulting doctor after stent'],
    interactions: ['Aspirin', 'NSAIDs', 'Proton pump inhibitors (especially omeprazole)', 'Warfarin'],
    prescription: true,
    storage: 'Store at room temperature away from moisture.',
    alternatives: ['Ticagrelor', 'Prasugrel', 'Aspirin'],
  },
  {
    id: 'digoxin', name: 'Digoxin', generic: 'Digoxin',
    brands: ['Lanoxin', 'Digoxin Nativelle'],
    category: 'Heart Health',
    usage: 'Heart failure and atrial fibrillation — slows and strengthens the heartbeat.',
    dosage: 'Adults: 0.125–0.25 mg once daily. Narrow therapeutic window — individualized dosing.',
    sideEffects: ['Nausea', 'Vomiting', 'Visual disturbances (yellow-green halos)', 'Bradycardia', 'Arrhythmias'],
    warnings: ['Very narrow therapeutic range (toxicity risk)', 'Monitor blood levels regularly', 'Hypokalemia increases toxicity risk', 'Reduce dose in kidney disease'],
    interactions: ['Amiodarone', 'Verapamil', 'Clarithromycin', 'Rifampicin', 'Diuretics (electrolyte changes)'],
    prescription: true,
    storage: 'Store at room temperature, protect from light.',
    alternatives: ['Beta-blockers (for rate control)', 'Amiodarone', 'Ivabradine'],
  },
  {
    id: 'isosorbide-mononitrate', name: 'Isosorbide Mononitrate', generic: 'Isosorbide mononitrate',
    brands: ['Imdur', 'Ismo', 'Monotrate'],
    category: 'Heart Health',
    usage: 'Prevention of angina. Long-acting nitrate that dilates coronary arteries.',
    dosage: 'Immediate release: 20 mg twice daily (allow 7-hour nitrate-free interval). Extended-release: 30–120 mg once daily.',
    sideEffects: ['Headache (common, improves with time)', 'Flushing', 'Dizziness', 'Low blood pressure'],
    warnings: ['Tolerance develops with continuous use — maintain nitrate-free interval', 'Do not stop abruptly', 'Never take with Sildenafil (Viagra) — severe hypotension'],
    interactions: ['Sildenafil/Tadalafil (contraindicated)', 'Antihypertensives', 'Alcohol'],
    prescription: true,
    storage: 'Store at room temperature, away from heat and light.',
    alternatives: ['Isosorbide dinitrate', 'Glyceryl trinitrate (for acute attacks)', 'Amlodipine'],
  },

  // ── VITAMINS & SUPPLEMENTS ─────────────────────────────────────────────────
  {
    id: 'vit-d3', name: 'Vitamin D3', generic: 'Cholecalciferol',
    brands: ['Calcirol', 'Arachitol', 'D-Rise', 'Uprise D3'],
    category: 'Vitamins & Supplements',
    usage: 'Vitamin D deficiency, bone health, immune support, muscle function. Very common deficiency in India.',
    dosage: 'Deficiency treatment: 60,000 IU once weekly for 8–12 weeks, then 2000 IU daily. Maintenance: 1000–2000 IU daily.',
    sideEffects: ['Usually none at recommended doses. Toxicity (high doses): nausea, weakness, hypercalcemia, kidney stones'],
    warnings: ['High doses require doctor supervision', 'Take with fatty food for better absorption', 'Monitor calcium levels with high-dose therapy'],
    interactions: ['Thiazide diuretics (hypercalcemia risk)', 'Digoxin'],
    prescription: false,
    storage: 'Store in cool, dry place away from light.',
    alternatives: ['Vitamin D2 (ergocalciferol)', 'Calcitriol (active form for kidney disease)'],
  },
  {
    id: 'vit-b12', name: 'Vitamin B12', generic: 'Cyanocobalamin / Methylcobalamin',
    brands: ['Methylcobalamin', 'Becosules', 'Cobadex', 'Mecoblamin'],
    category: 'Vitamins & Supplements',
    usage: 'B12 deficiency (especially vegetarians), pernicious anemia, neuropathy, fatigue.',
    dosage: 'Deficiency: 1000 mcg daily for 2 weeks, then weekly, then monthly (injectable). Oral: 1000–2000 mcg daily.',
    sideEffects: ['Generally very safe. Rare: mild diarrhea, itching, rash'],
    warnings: ['Vegetarians and vegans are high risk for deficiency', 'Metformin users need monitoring', 'Injections needed if absorption is impaired'],
    interactions: ['Metformin', 'Proton pump inhibitors', 'H2 blockers'],
    prescription: false,
    storage: 'Store at room temperature, away from light.',
    alternatives: ['Hydroxocobalamin (injectable)', 'Adenosylcobalamin'],
  },
  {
    id: 'folic-acid', name: 'Folic Acid', generic: 'Folic acid (Vitamin B9)',
    brands: ['Folicid', 'Vitcofol', 'Folvite'],
    category: 'Vitamins & Supplements',
    usage: 'Pregnancy (neural tube defect prevention), megaloblastic anemia, folate deficiency, methotrexate supplementation.',
    dosage: 'Pregnancy prevention: 400–800 mcg daily. Treatment of deficiency: 5 mg daily. With methotrexate: 5 mg/week.',
    sideEffects: ['Very rare: nausea, loss of appetite, bloating'],
    warnings: ['Should be started before pregnancy if planning', 'Can mask B12 deficiency — check B12 first', 'High dose in epilepsy may alter seizure control'],
    interactions: ['Methotrexate', 'Antiepileptics (phenytoin, carbamazepine)'],
    prescription: false,
    storage: 'Store at room temperature, away from light and moisture.',
    alternatives: ['Methylfolate (for MTHFR gene variants)', 'Folinic acid'],
  },
  {
    id: 'iron', name: 'Iron (Ferrous Sulfate)', generic: 'Ferrous sulfate',
    brands: ['Ferrous Sulfate', 'Ferodan', 'Tardyferon', 'Livogen'],
    category: 'Vitamins & Supplements',
    usage: 'Iron deficiency anemia — very common in women and children in India.',
    dosage: 'Adults: 200 mg (60 mg elemental iron) 1–3 times daily. Children: 3–6 mg/kg/day of elemental iron.',
    sideEffects: ['Constipation', 'Dark stools', 'Nausea', 'Stomach cramps', 'Heartburn'],
    warnings: ['Take on empty stomach for best absorption (or with Vitamin C)', 'Dark stools are normal — not GI bleeding', 'Keep away from children (overdose is serious)', 'Separate from antacids by 2 hours'],
    interactions: ['Antacids', 'Calcium supplements', 'Tetracyclines', 'Levothyroxine', 'Proton pump inhibitors'],
    prescription: false,
    storage: 'Store in cool, dry place. Keep tightly closed.',
    alternatives: ['Ferrous gluconate', 'Iron polymaltose', 'IV iron (for severe cases)'],
  },
  {
    id: 'calcium', name: 'Calcium Carbonate', generic: 'Calcium carbonate',
    brands: ['Shelcal', 'Calcimax', 'Calcitas', 'Tums'],
    category: 'Vitamins & Supplements',
    usage: 'Calcium deficiency, osteoporosis prevention, antacid (for heartburn).',
    dosage: 'Supplementation: 500–1200 mg elemental calcium daily in divided doses. Antacid: 500–1500 mg as needed.',
    sideEffects: ['Constipation', 'Gas', 'Bloating', 'Kidney stones (with very high doses)'],
    warnings: ['Take with Vitamin D for better absorption', 'Separate from iron supplements by 2 hours', 'Large doses may increase cardiovascular risk — stay within recommended levels'],
    interactions: ['Iron', 'Levothyroxine', 'Ciprofloxacin', 'Tetracyclines', 'Bisphosphonates'],
    prescription: false,
    storage: 'Store at room temperature, away from moisture.',
    alternatives: ['Calcium citrate (better absorbed)', 'Calcium gluconate'],
  },
  {
    id: 'omega3', name: 'Omega-3 Fatty Acids', generic: 'EPA + DHA fish oil',
    brands: ['Econorm', 'Maxepa', 'Omacor', 'Zodin'],
    category: 'Vitamins & Supplements',
    usage: 'Cardiovascular health, triglyceride reduction, joint health, brain health.',
    dosage: 'General health: 1000 mg daily. Triglyceride lowering: 2000–4000 mg/day (prescription-grade).',
    sideEffects: ['Fishy aftertaste', 'Burping', 'Nausea', 'Diarrhea', 'Mild blood-thinning effect'],
    warnings: ['May affect platelet function — caution before surgery', 'High doses may increase bleeding risk', 'Beware of mercury in low-quality supplements'],
    interactions: ['Warfarin', 'Aspirin', 'Antiplatelet drugs'],
    prescription: false,
    storage: 'Refrigerate after opening to prevent rancidity.',
    alternatives: ['Flaxseed oil (ALA)', 'Algae-based DHA (vegan option)'],
  },

  // ── DIGESTIVE HEALTH ───────────────────────────────────────────────────────
  {
    id: 'omeprazole', name: 'Omeprazole', generic: 'Omeprazole',
    brands: ['Prilosec', 'Omez', 'Ocid', 'Omparib'],
    category: 'Digestive Health',
    usage: 'Peptic ulcer disease, GERD (acid reflux), H. pylori eradication (with antibiotics), Zollinger-Ellison syndrome.',
    dosage: 'GERD: 20 mg once daily before breakfast for 4–8 weeks. Ulcers: 20–40 mg daily. H. pylori: 20 mg twice daily (with antibiotics).',
    sideEffects: ['Headache', 'Diarrhea', 'Nausea', 'Low magnesium (long-term)', 'C. difficile risk', 'Reduced calcium absorption'],
    warnings: ['Long-term use: risk of B12 deficiency, hypomagnesemia, bone fractures', 'Review need for PPI regularly', 'Reduces clopidogrel effectiveness'],
    interactions: ['Clopidogrel', 'Methotrexate', 'Citalopram', 'Iron supplements'],
    prescription: false,
    storage: 'Store at room temperature, away from moisture and heat.',
    alternatives: ['Pantoprazole', 'Rabeprazole', 'Esomeprazole', 'Ranitidine (H2 blocker)'],
  },
  {
    id: 'pantoprazole', name: 'Pantoprazole', generic: 'Pantoprazole sodium',
    brands: ['Pantocid', 'Pantop', 'Protonix'],
    category: 'Digestive Health',
    usage: 'Acid reflux, GERD, ulcers. Fewer drug interactions than omeprazole.',
    dosage: 'Adults: 40 mg once daily before breakfast. Severe cases: 40 mg twice daily.',
    sideEffects: ['Headache', 'Diarrhea', 'Abdominal pain', 'Nausea', 'Hypomagnesemia (long-term)'],
    warnings: ['Similar long-term concerns as omeprazole', 'Does not significantly impair clopidogrel — preferred in cardiac patients'],
    interactions: ['Methotrexate', 'Atazanavir', 'Iron supplements'],
    prescription: false,
    storage: 'Store at room temperature, protect from light.',
    alternatives: ['Omeprazole', 'Esomeprazole', 'Rabeprazole'],
  },
  {
    id: 'ondansetron', name: 'Ondansetron', generic: 'Ondansetron hydrochloride',
    brands: ['Zofran', 'Emeset', 'Ondem', 'Ondansetron'],
    category: 'Digestive Health',
    usage: 'Nausea and vomiting caused by chemotherapy, radiotherapy, and surgery.',
    dosage: 'Adults: 8 mg twice daily or 8 mg before procedure. IV/IM: 4 mg.',
    sideEffects: ['Headache', 'Constipation', 'Flushing', 'Dizziness', 'QT prolongation (rare)'],
    warnings: ['Risk of QT prolongation — avoid with other QT-prolonging drugs', 'Constipation may be significant with repeated dosing'],
    interactions: ['Other QT-prolonging drugs', 'Tramadol', 'Apomorphine (contraindicated)'],
    prescription: true,
    storage: 'Store at room temperature, protect from light.',
    alternatives: ['Metoclopramide', 'Domperidone', 'Granisetron'],
  },
  {
    id: 'metoclopramide', name: 'Metoclopramide', generic: 'Metoclopramide hydrochloride',
    brands: ['Reglan', 'Perinorm', 'Maxolon'],
    category: 'Digestive Health',
    usage: 'Nausea, vomiting, gastric stasis, GERD, hiccups. Speeds up gastric emptying.',
    dosage: 'Adults: 10 mg up to three times daily, 30 minutes before meals.',
    sideEffects: ['Drowsiness', 'Restlessness', 'Tardive dyskinesia (with long-term use)', 'Extrapyramidal effects (muscle movements)'],
    warnings: ['Do not use for more than 3 months', 'Tardive dyskinesia risk with long-term use', 'Caution in Parkinson\'s disease', 'Not for people with GI obstruction'],
    interactions: ['Antipsychotics', 'Opioids', 'Alcohol', 'Digoxin'],
    prescription: false,
    storage: 'Store at room temperature, protect from light.',
    alternatives: ['Ondansetron', 'Domperidone', 'Prochlorperazine'],
  },
  {
    id: 'loperamide', name: 'Loperamide', generic: 'Loperamide hydrochloride',
    brands: ['Imodium', 'Lopamide', 'Eldoper'],
    category: 'Digestive Health',
    usage: 'Acute and chronic diarrhea. Slows gut movement and reduces frequency of stools.',
    dosage: 'Adults: 4 mg initially, then 2 mg after each loose stool. Max 16 mg/day. Children 9–12: 2 mg up to 3 times/day.',
    sideEffects: ['Constipation', 'Abdominal cramps', 'Dizziness', 'Nausea'],
    warnings: ['Do not use in bacterial infections with high fever/bloody stools (consult doctor)', 'Do not use in children under 2 years', 'Seek help if diarrhea persists more than 2 days'],
    interactions: ['Quinidine', 'Ritonavir', 'Saquinavir'],
    prescription: false,
    storage: 'Store at room temperature.',
    alternatives: ['Oral rehydration salts (ORS)', 'Bismuth subsalicylate', 'Zinc (for children)'],
  },
  {
    id: 'lactulose', name: 'Lactulose', generic: 'Lactulose',
    brands: ['Duphalac', 'Lactulos', 'Kristalose'],
    category: 'Digestive Health',
    usage: 'Constipation and hepatic encephalopathy. Draws water into the colon to soften stools.',
    dosage: 'Constipation: 15–30 mL once or twice daily. Hepatic encephalopathy: 30–45 mL 3–4 times daily.',
    sideEffects: ['Gas', 'Bloating', 'Abdominal cramps', 'Diarrhea (with excess dose)', 'Nausea'],
    warnings: ['Patients with diabetes should use with caution (contains galactose)', 'Adjust dose to achieve 2–3 soft stools/day', 'Avoid if GI obstruction suspected'],
    interactions: ['Antacids', 'Antibiotics (reduce efficacy in hepatic encephalopathy)'],
    prescription: false,
    storage: 'Store at room temperature.',
    alternatives: ['Ispaghula (Psyllium)', 'Bisacodyl', 'Senna', 'PEG (polyethylene glycol)'],
  },

  // ── ANTIBIOTICS ────────────────────────────────────────────────────────────
  {
    id: 'amoxicillin', name: 'Amoxicillin', generic: 'Amoxicillin trihydrate',
    brands: ['Amoxil', 'Trimox', 'Mox', 'Novamox'],
    category: 'Antibiotics',
    usage: 'Bacterial infections: ear, throat, chest, urinary tract, H. pylori eradication (with other agents).',
    dosage: 'Adults: 250–500 mg three times daily or 875 mg twice daily. Severe: 875–1000 mg twice daily.',
    sideEffects: ['Diarrhea', 'Nausea', 'Rash', 'Allergic reaction (penicillin allergy)', 'Vomiting'],
    warnings: ['Check for penicillin allergy before use', 'Complete the full course', 'Diarrhea may suggest C. difficile infection'],
    interactions: ['Warfarin', 'Oral contraceptives (reduced efficacy claim — take precautions)', 'Allopurinol (increases rash risk)', 'Methotrexate'],
    prescription: true,
    storage: 'Store tablets at room temperature. Suspension: refrigerate, discard after 10 days.',
    alternatives: ['Azithromycin', 'Co-amoxiclav', 'Clarithromycin'],
  },
  {
    id: 'azithromycin', name: 'Azithromycin', generic: 'Azithromycin dihydrate',
    brands: ['Zithromax', 'Azee', 'Azithral', 'Zithrox'],
    category: 'Antibiotics',
    usage: 'Respiratory infections (community pneumonia, bronchitis), STIs (chlamydia), skin infections, otitis media.',
    dosage: 'Adults: 500 mg on day 1, then 250 mg once daily for 4 more days (5-day course). Or 500 mg once daily for 3 days.',
    sideEffects: ['Diarrhea', 'Nausea', 'Abdominal pain', 'QT prolongation (cardiac risk)', 'Vomiting'],
    warnings: ['QT prolongation risk — avoid with other QT-prolonging drugs', 'Warn about persistent diarrhea', 'Resistance is increasing — use only when appropriate'],
    interactions: ['Warfarin', 'Digoxin', 'Antacids (take 1 hour before or 2 hours after)', 'QT-prolonging drugs'],
    prescription: true,
    storage: 'Store at room temperature. Suspension: discard after 10 days.',
    alternatives: ['Clarithromycin', 'Amoxicillin', 'Doxycycline'],
  },
  {
    id: 'doxycycline', name: 'Doxycycline', generic: 'Doxycycline hyclate',
    brands: ['Vibramycin', 'Doxrid', 'Biodoxi', 'Supracycline'],
    category: 'Antibiotics',
    usage: 'Respiratory tract infections, acne, chlamydia, Lyme disease, malaria prevention, urinary tract infections.',
    dosage: 'Adults: 100 mg twice daily on day 1, then 100 mg once daily. Acne: 50–100 mg once daily.',
    sideEffects: ['Photosensitivity (sunburn risk)', 'Nausea', 'Esophageal irritation', 'Yeast infections (women)', 'Diarrhea'],
    warnings: ['Take with plenty of water, remain upright for 30 minutes', 'Avoid sun exposure — use SPF 50+', 'Not for children under 8 (affects tooth development)', 'Avoid in pregnancy'],
    interactions: ['Antacids', 'Calcium/iron supplements', 'Rifampicin', 'Warfarin', 'Oral contraceptives'],
    prescription: true,
    storage: 'Store at room temperature, protect from light and moisture.',
    alternatives: ['Azithromycin', 'Amoxicillin', 'Minocycline'],
  },
  {
    id: 'ciprofloxacin', name: 'Ciprofloxacin', generic: 'Ciprofloxacin hydrochloride',
    brands: ['Cipro', 'Ciplox', 'Cifran', 'Quintor'],
    category: 'Antibiotics',
    usage: 'Urinary tract infections, traveler\'s diarrhea, prostatitis, bone and joint infections.',
    dosage: 'UTI uncomplicated: 250–500 mg twice daily for 3–7 days. Severe infections: 500–750 mg twice daily for 10–14 days.',
    sideEffects: ['Nausea', 'Diarrhea', 'Headache', 'Dizziness', 'Tendinitis (especially Achilles tendon)', 'QT prolongation'],
    warnings: ['Risk of tendon rupture — stop immediately if tendon pain', 'Not for children under 18 (cartilage risk)', 'Avoid excessive sunlight', 'May worsen myasthenia gravis'],
    interactions: ['Antacids/dairy (take 2 hours apart)', 'Warfarin', 'Theophylline', 'NSAIDs'],
    prescription: true,
    storage: 'Store at room temperature, away from light.',
    alternatives: ['Nitrofurantoin (for UTI)', 'Levofloxacin', 'Trimethoprim'],
  },
  {
    id: 'metronidazole', name: 'Metronidazole', generic: 'Metronidazole',
    brands: ['Flagyl', 'Metrogyl', 'Metronidazole'],
    category: 'Antibiotics',
    usage: 'Anaerobic bacterial infections, protozoal infections (amoeba, giardia), H. pylori, bacterial vaginosis, dental infections.',
    dosage: 'Adults: 400–500 mg three times daily for 5–10 days. Protozoal: doses vary by infection type.',
    sideEffects: ['Metallic taste', 'Nausea', 'Headache', 'Dizziness', 'Dark urine (harmless)'],
    warnings: ['Strict avoidance of alcohol during treatment AND 48 hours after (severe reaction)', 'May darken urine (normal)', 'Avoid in first trimester of pregnancy'],
    interactions: ['Alcohol (severe disulfiram-like reaction)', 'Warfarin', 'Lithium', 'Ciclosporin'],
    prescription: true,
    storage: 'Store at room temperature, protect from light.',
    alternatives: ['Tinidazole', 'Ornidazole', 'Secnidazole'],
  },

  // ── SKIN CARE ──────────────────────────────────────────────────────────────
  {
    id: 'clotrimazole', name: 'Clotrimazole', generic: 'Clotrimazole',
    brands: ['Canesten', 'Surfaz', 'Candid', 'Clotrimac'],
    category: 'Skin Care',
    usage: 'Fungal skin infections: ringworm, athlete\'s foot, jock itch, candidal infections, vaginal thrush.',
    dosage: 'Apply thin layer to affected area 2–3 times daily for 4 weeks. Continue for 1 week after symptoms resolve.',
    sideEffects: ['Mild skin irritation', 'Burning sensation (initially)', 'Redness', 'Peeling'],
    warnings: ['Avoid eyes and mucous membranes', 'Continue full course', 'If no improvement in 4 weeks, see a doctor'],
    interactions: ['Minimal systemic interactions with topical use'],
    prescription: false,
    storage: 'Store at room temperature, away from direct sunlight.',
    alternatives: ['Fluconazole (oral for persistent cases)', 'Terbinafine', 'Miconazole'],
  },
  {
    id: 'benzoyl-peroxide', name: 'Benzoyl Peroxide', generic: 'Benzoyl peroxide',
    brands: ['Benzac', 'Panoxyl', 'Acne-Aid', 'Persol'],
    category: 'Skin Care',
    usage: 'Acne treatment — kills P. acnes bacteria, reduces inflammation and oil production.',
    dosage: 'Apply to clean, dry skin once or twice daily. Start with 2.5% and increase gradually.',
    sideEffects: ['Dryness', 'Peeling', 'Redness', 'Stinging', 'Bleaching of fabric/hair'],
    warnings: ['Bleaches clothing, towels, and hair', 'Use SPF during the day', 'Start with lower concentrations', 'Avoid contact with eyes'],
    interactions: ['Retinoids (use at different times of day)', 'Other acne topicals'],
    prescription: false,
    storage: 'Store at room temperature, away from heat.',
    alternatives: ['Salicylic acid', 'Adapalene (retinoid)', 'Azelaic acid'],
  },
  {
    id: 'tretinoin', name: 'Tretinoin', generic: 'Tretinoin (all-trans retinoic acid)',
    brands: ['Retin-A', 'Retino-A', 'Retrieve'],
    category: 'Skin Care',
    usage: 'Acne, anti-aging, hyperpigmentation, keratosis pilaris.',
    dosage: 'Apply pea-sized amount to clean, dry face once daily at night. Start with 0.025%.',
    sideEffects: ['Dryness', 'Peeling', 'Redness', 'Photosensitivity', 'Initial acne flare (purging)'],
    warnings: ['Always use sunscreen during the day', 'Avoid in pregnancy — teratogenic', 'Initial purging may occur for 4–6 weeks', 'Avoid with waxing or harsh scrubs'],
    interactions: ['Benzoyl peroxide (use at different times)', 'Photosensitizing drugs', 'Salicylic acid'],
    prescription: true,
    storage: 'Store in refrigerator or cool, dark place.',
    alternatives: ['Adapalene', 'Tazarotene', 'Bakuchiol (natural alternative)'],
  },
  {
    id: 'mupirocin', name: 'Mupirocin', generic: 'Mupirocin',
    brands: ['Bactroban', 'Mupicin', 'Oint-Mupis'],
    category: 'Skin Care',
    usage: 'Bacterial skin infections: impetigo, infected wounds, folliculitis. Also nasal decolonization of MRSA.',
    dosage: 'Apply to affected area 3 times daily for 5–10 days. Nasal: apply twice daily for 5 days.',
    sideEffects: ['Local burning', 'Stinging', 'Itching'],
    warnings: ['For external use only', 'Do not use in the eyes or on large areas of skin', 'Resistance may develop with overuse'],
    interactions: ['Minimal with topical use'],
    prescription: true,
    storage: 'Store at room temperature.',
    alternatives: ['Fusidic acid cream', 'Neomycin cream', 'Bacitracin'],
  },

  // ── MENTAL HEALTH ──────────────────────────────────────────────────────────
  {
    id: 'sertraline', name: 'Sertraline', generic: 'Sertraline hydrochloride',
    brands: ['Zoloft', 'Serlift', 'Daxid', 'Serta'],
    category: 'Mental Health',
    usage: 'Depression, OCD, panic disorder, PTSD, social anxiety disorder, premenstrual dysphoric disorder.',
    dosage: 'Start: 50 mg once daily. Usual: 50–200 mg once daily. Increase by 50 mg every 2 weeks if needed.',
    sideEffects: ['Nausea', 'Diarrhea', 'Insomnia or drowsiness', 'Sweating', 'Sexual dysfunction', 'Headache'],
    warnings: ['Increased suicidal thoughts in under-25s at treatment start — monitor closely', 'Do not stop abruptly', 'Take 2–4 weeks for effect to start', 'Serotonin syndrome with MAO inhibitors (contraindicated)'],
    interactions: ['MAO inhibitors (contraindicated)', 'Warfarin', 'Tramadol', 'Pimozide (contraindicated)', 'NSAIDs (bleeding risk)'],
    prescription: true,
    storage: 'Store at room temperature, away from light.',
    alternatives: ['Escitalopram', 'Fluoxetine', 'Paroxetine'],
  },
  {
    id: 'escitalopram', name: 'Escitalopram', generic: 'Escitalopram oxalate',
    brands: ['Lexapro', 'Nexito', 'Cipralex', 'Stalopam'],
    category: 'Mental Health',
    usage: 'Depression and generalized anxiety disorder. One of the most well-tolerated SSRIs.',
    dosage: 'Start: 10 mg once daily. May increase to 20 mg after 2–4 weeks.',
    sideEffects: ['Nausea', 'Dry mouth', 'Insomnia', 'Sweating', 'Sexual dysfunction'],
    warnings: ['Monitor for suicidality at start', 'QT prolongation at higher doses', 'Taper slowly when discontinuing', 'Takes 2–6 weeks for full effect'],
    interactions: ['MAO inhibitors (contraindicated)', 'Pimozide', 'Clopidogrel', 'NSAIDs'],
    prescription: true,
    storage: 'Store at room temperature.',
    alternatives: ['Sertraline', 'Fluoxetine', 'Venlafaxine'],
  },
  {
    id: 'alprazolam', name: 'Alprazolam', generic: 'Alprazolam',
    brands: ['Xanax', 'Alprax', 'Restyl', 'Tranax'],
    category: 'Mental Health',
    usage: 'Short-term treatment of anxiety disorders and panic disorder. NOT for long-term use.',
    dosage: 'Anxiety: 0.25–0.5 mg three times daily. Max 4 mg/day. Use lowest effective dose, shortest time.',
    sideEffects: ['Sedation', 'Dizziness', 'Cognitive impairment', 'Dependence and withdrawal', 'Rebound anxiety'],
    warnings: ['High dependence and addiction potential', 'Do not stop abruptly (seizure risk)', 'Avoid with opioids — fatal respiratory depression risk', 'Avoid in pregnancy', 'Avoid alcohol'],
    interactions: ['Opioids (fatal combination)', 'Alcohol', 'Other CNS depressants', 'Ketoconazole', 'Itraconazole'],
    prescription: true,
    storage: 'Store at room temperature, away from moisture and heat.',
    alternatives: ['SSRIs/SNRIs (for long-term anxiety)', 'Buspirone', 'Hydroxyzine'],
  },
  {
    id: 'quetiapine', name: 'Quetiapine', generic: 'Quetiapine fumarate',
    brands: ['Seroquel', 'Qutipin', 'Quetiax'],
    category: 'Mental Health',
    usage: 'Schizophrenia, bipolar disorder (mania and depression), adjunct in major depression.',
    dosage: 'Schizophrenia: Start 25 mg twice daily, titrate to 300–450 mg/day. Bipolar: Similar escalation.',
    sideEffects: ['Sedation', 'Weight gain', 'Dry mouth', 'Constipation', 'Metabolic changes', 'QT prolongation', 'Orthostatic hypotension'],
    warnings: ['Monitor metabolic parameters (weight, blood sugar, lipids)', 'Elderly with dementia: increased mortality risk', 'Risk of tardive dyskinesia with long-term use'],
    interactions: ['Alcohol', 'CNS depressants', 'QT-prolonging drugs', 'CYP3A4 inhibitors/inducers'],
    prescription: true,
    storage: 'Store at room temperature, away from light.',
    alternatives: ['Olanzapine', 'Risperidone', 'Aripiprazole'],
  },

  // ── RESPIRATORY HEALTH ─────────────────────────────────────────────────────
  {
    id: 'salbutamol', name: 'Salbutamol (Albuterol)', generic: 'Salbutamol sulfate',
    brands: ['Ventolin', 'Asthalin', 'Levolin', 'Salbair'],
    category: 'Respiratory Health',
    usage: 'Acute asthma, exercise-induced bronchoconstriction, COPD (rescue inhaler). Short-acting bronchodilator.',
    dosage: 'Inhaler: 1–2 puffs (100 mcg each) every 4–6 hours as needed. Nebulizer: 2.5 mg every 4–6 hours. Oral: 2–4 mg 3–4 times daily.',
    sideEffects: ['Tremor', 'Palpitations', 'Headache', 'Nervousness', 'Low potassium (high doses)'],
    warnings: ['If using rescue inhaler more than 2 days/week, see doctor for better control', 'Do not exceed prescribed dose', 'Check inhaler technique'],
    interactions: ['Beta-blockers (reduced effect)', 'Digoxin (increased risk of arrhythmia)', 'MAO inhibitors'],
    prescription: true,
    storage: 'Store at room temperature, protect from frost and sunlight. Discard 12 months after opening.',
    alternatives: ['Terbutaline', 'Ipratropium (for COPD)', 'Formoterol (long-acting)'],
  },
  {
    id: 'budesonide', name: 'Budesonide Inhaler', generic: 'Budesonide',
    brands: ['Pulmicort', 'Budecort', 'Budesal'],
    category: 'Respiratory Health',
    usage: 'Preventive treatment of asthma and COPD. Inhaled corticosteroid — reduces airway inflammation.',
    dosage: 'Mild asthma: 200–400 mcg twice daily. Moderate: 400–800 mcg twice daily. Max 1600 mcg/day.',
    sideEffects: ['Oral thrush (candidiasis)', 'Hoarseness', 'Cough', 'Throat irritation', 'Systemic effects rare at low doses'],
    warnings: ['Rinse mouth after each use to prevent oral thrush', 'Does NOT give immediate relief (not a rescue inhaler)', 'Carry a rescue inhaler as well', 'Do not stop abruptly'],
    interactions: ['CYP3A4 inhibitors (ketoconazole, itraconazole) increase systemic absorption'],
    prescription: true,
    storage: 'Store at room temperature, away from frost.',
    alternatives: ['Fluticasone', 'Beclometasone', 'Ciclesonide'],
  },
  {
    id: 'levothyroxine', name: 'Levothyroxine', generic: 'Levothyroxine sodium',
    brands: ['Synthroid', 'Eltroxin', 'Thyronorm', 'ThyroMed'],
    category: 'Respiratory Health',
    usage: 'Hypothyroidism (underactive thyroid) replacement therapy.',
    dosage: 'Start: 25–50 mcg once daily (lower in elderly or cardiac patients). Adjust by 12.5–25 mcg every 4–6 weeks. Usual: 100–200 mcg/day.',
    sideEffects: ['At correct dose: none. Overdose: palpitations, weight loss, sweating, insomnia, tremor, diarrhea'],
    warnings: ['Take on empty stomach 30–60 minutes before breakfast', 'Take consistently — same brand if possible', 'Monitor TSH levels every 6–12 months once stable'],
    interactions: ['Calcium, iron, antacids (take 4 hours apart)', 'Warfarin', 'Statins', 'Rifampicin'],
    prescription: true,
    storage: 'Store at room temperature, protect from light and moisture.',
    alternatives: ['Liothyronine (T3) in special cases'],
  },

  // ── WOMEN'S HEALTH ─────────────────────────────────────────────────────────
  {
    id: 'ethinylestradiol', name: 'Combined OCP (Ethinylestradiol + Levonorgestrel)', generic: 'Ethinylestradiol + Levonorgestrel',
    brands: ['Ovral-L', 'Loette', 'Trust', 'Mala-D'],
    category: 'Women\'s Health',
    usage: 'Contraception, regulation of menstrual cycle, dysmenorrhea.',
    dosage: 'One tablet daily at the same time each day for 21 days, then 7-day break. Start on day 1–5 of cycle.',
    sideEffects: ['Nausea', 'Breast tenderness', 'Headache', 'Mood changes', 'Reduced libido', 'Spotting (first months)'],
    warnings: ['Increased risk of blood clots (DVT) — especially smokers over 35', 'Do not smoke while on OCP', 'Risk of hypertension', 'May decrease milk supply (breastfeeding)'],
    interactions: ['Rifampicin (renders OCP ineffective)', 'Antiepileptics', 'St. John\'s Wort', 'Broad-spectrum antibiotics'],
    prescription: true,
    storage: 'Store at room temperature, away from moisture.',
    alternatives: ['Progestogen-only pill', 'Copper IUD', 'Implant'],
  },
  {
    id: 'progesterone', name: 'Progesterone', generic: 'Micronized progesterone',
    brands: ['Duphaston (dydrogesterone)', 'Susten', 'Uterogen', 'Gestofit'],
    category: 'Women\'s Health',
    usage: 'Luteal phase support in IVF, threatened miscarriage, irregular periods, HRT.',
    dosage: 'IVF support: 200–400 mg vaginally twice daily. Irregular periods: 10–20 mg orally for 10–14 days.',
    sideEffects: ['Drowsiness', 'Headache', 'Dizziness', 'Breast tenderness', 'Nausea'],
    warnings: ['Vaginal form preferred for IVF (less drowsiness)', 'Oral form should be taken at bedtime', 'Monitor regularly in pregnancy'],
    interactions: ['CYP3A4 inducers/inhibitors', 'Ketoconazole'],
    prescription: true,
    storage: 'Store at room temperature, away from light.',
    alternatives: ['Dydrogesterone', 'Medroxyprogesterone acetate'],
  },
  {
    id: 'iron-folic', name: 'Iron + Folic Acid (Pregnancy)', generic: 'Ferrous fumarate + Folic acid',
    brands: ['Feronia XT', 'Pregaday', 'Obimin', 'Fefol'],
    category: 'Women\'s Health',
    usage: 'Prevention and treatment of iron deficiency anemia in pregnancy. Neural tube defect prevention.',
    dosage: 'One tablet daily. Pregnant women should continue throughout pregnancy and 3 months postpartum.',
    sideEffects: ['Constipation', 'Dark stools', 'Nausea', 'Stomach cramps'],
    warnings: ['Take on empty stomach or with Vitamin C for better absorption', 'Keep away from children', 'Separate from calcium by 2 hours'],
    interactions: ['Calcium', 'Antacids', 'Tetracyclines', 'Levothyroxine'],
    prescription: false,
    storage: 'Store in cool, dry place.',
    alternatives: ['IV iron sucrose (severe anemia)', 'Separate iron + folic supplements'],
  },

  // ── CHILDREN'S MEDICINES ───────────────────────────────────────────────────
  {
    id: 'paracetamol-syrup', name: 'Paracetamol Syrup (Children)', generic: 'Acetaminophen',
    brands: ['Calpol Syrup', 'Fepanil', 'Mefacin DS', 'Dolopar'],
    category: 'Children\'s Medicines',
    usage: 'Fever and mild pain in infants and children (teething, vaccination reactions, cold, flu).',
    dosage: 'Infants/children: 10–15 mg/kg every 4–6 hours. Max 5 doses in 24 hours. Use weight-based dosing chart.',
    sideEffects: ['Rare at correct doses. Overdose: liver damage'],
    warnings: ['Always dose by weight, not age', 'Do not give alongside other paracetamol-containing products', 'Seek emergency care for overdose'],
    interactions: ['Other paracetamol-containing medicines'],
    prescription: false,
    storage: 'Store at room temperature. Do not refrigerate.',
    alternatives: ['Ibuprofen syrup (6 months+)', 'Tepid sponging for fever'],
  },
  {
    id: 'ibuprofen-syrup', name: 'Ibuprofen Syrup (Children)', generic: 'Ibuprofen',
    brands: ['Brufen Syrup', 'Combiflam Suspension', 'Emflam'],
    category: 'Children\'s Medicines',
    usage: 'Fever, pain, and inflammation in children from 6 months of age.',
    dosage: '5–10 mg/kg every 6–8 hours. Max 30–40 mg/kg/day. Give with food.',
    sideEffects: ['Stomach upset', 'Nausea', 'Rash'],
    warnings: ['Not for infants under 6 months', 'Take with food', 'Do not give with dehydration — kidney risk', 'Do not use in chickenpox'],
    interactions: ['Aspirin', 'Other NSAIDs', 'Warfarin'],
    prescription: false,
    storage: 'Store at room temperature. Discard after 6 months from opening.',
    alternatives: ['Paracetamol syrup', 'Naproxen (older children)'],
  },
  {
    id: 'zinc-oral', name: 'Zinc Sulfate (Children)', generic: 'Zinc sulfate monohydrate',
    brands: ['Zincovit', 'Zevit', 'Zincolak syrup'],
    category: 'Children\'s Medicines',
    usage: 'Treatment of acute diarrhea in children (WHO-recommended), zinc deficiency, growth support.',
    dosage: 'Diarrhea: Children < 6 months: 10 mg/day for 14 days. 6 months+: 20 mg/day for 14 days.',
    sideEffects: ['Nausea', 'Vomiting (with high doses)', 'Stomach cramps'],
    warnings: ['Give with ORS for diarrhea', 'Do not exceed recommended dose', 'Reduces severity and duration of diarrhea'],
    interactions: ['Tetracyclines', 'Fluoroquinolones', 'Iron (separate by 2 hours)'],
    prescription: false,
    storage: 'Store at room temperature.',
    alternatives: ['ORS (always first-line for diarrhea)', 'Probiotic sachets'],
  },
  {
    id: 'pedialyte', name: 'ORS (Oral Rehydration Salts)', generic: 'Sodium chloride + Potassium + Glucose',
    brands: ['ORS Sachet', 'Electral', 'Pedialyte', 'Enfalyte'],
    category: 'Children\'s Medicines',
    usage: 'Dehydration from diarrhea, vomiting, excessive sweating. First-line treatment for gastroenteritis.',
    dosage: 'Dissolve one sachet in 1 litre of clean water. Give small, frequent sips. Amount based on weight and severity of dehydration.',
    sideEffects: ['Rare: hypernatremia if prepared incorrectly (too little water)'],
    warnings: ['Always prepare with correct amount of water', 'Do not add extra sugar or salt', 'Seek medical help if vomiting prevents ORS use', 'Continue breastfeeding alongside ORS'],
    interactions: ['None of significance'],
    prescription: false,
    storage: 'Store sachets at room temperature. Reconstituted solution: use within 24 hours (refrigerate).',
    alternatives: ['Homemade sugar-salt solution (1 liter water, 6 tsp sugar, 0.5 tsp salt)', 'IV fluids (for severe dehydration)'],
  },
];

// ── Search helpers ──────────────────────────────────────────────────────────
export function searchMedicines(query: string, category?: MedCategory): MedicineEntry[] {
  const q = query.toLowerCase().trim();
  return MEDICINE_DB.filter(m => {
    const matchCategory = !category || m.category === category;
    if (!q) return matchCategory;
    const searchText = [
      m.name, m.generic,
      ...m.brands,
      m.usage,
      m.category,
      ...m.sideEffects,
    ].join(' ').toLowerCase();
    return matchCategory && searchText.includes(q);
  });
}

export function getMedicineById(id: string): MedicineEntry | undefined {
  return MEDICINE_DB.find(m => m.id === id);
}

export function getMedicinesByCategory(category: MedCategory): MedicineEntry[] {
  return MEDICINE_DB.filter(m => m.category === category);
}
